using System.Collections.Generic;
using Edpf.Abstractions.Data;

namespace Edpf.Data.Dialects;

/// <summary>SQL Server dialect — Tier A reference implementation (ADR-008).</summary>
public sealed class SqlServerDialect : SqlDialectBase
{
    /// <summary>The provider name this dialect serves.</summary>
    public const string Provider = "SqlServer";

    /// <inheritdoc />
    public override string ProviderName => Provider;

    /// <inheritdoc />
    protected override char QuoteOpen => '[';

    /// <inheritdoc />
    protected override char QuoteClose => ']';

    /// <inheritdoc />
    protected override int MaxIdentifierLength => 128;

    /// <inheritdoc />
    public override string PaginationClause(string skipParameter, string takeParameter)
        => $"OFFSET {Parameter(skipParameter)} ROWS FETCH NEXT {Parameter(takeParameter)} ROWS ONLY";

    /// <inheritdoc />
    /// <remarks>
    /// <c>SCOPE_IDENTITY()</c> rather than <c>@@IDENTITY</c>: the latter
    /// returns the identity generated by any trigger that fired, which is a
    /// classic source of wrong ids.
    /// </remarks>
    public override string IdentityRetrievalClause() => "SELECT CAST(SCOPE_IDENTITY() AS bigint)";

    /// <inheritdoc />
    public override string UtcNowExpression() => "SYSUTCDATETIME()";

    /// <inheritdoc />
    public override string Concat(IReadOnlyList<string> expressions)
        => expressions is { Count: > 0 }
            ? "CONCAT(" + string.Join(", ", expressions) + ")"
            : base.Concat(expressions!);

    /// <inheritdoc />
    public override string BooleanLiteral(bool value) => value ? "1" : "0";

    /// <inheritdoc />
    public override string JsonValue(string columnExpression, string jsonPathParameter)
        => $"JSON_VALUE({columnExpression}, {Parameter(jsonPathParameter)})";
}

/// <summary>SQL Server capabilities, declared honestly (ADR-016).</summary>
public sealed class SqlServerCapabilities : IProviderCapabilities
{
    /// <inheritdoc />
    public bool SupportsTableValuedParameters => true;

    /// <inheritdoc />
    public bool SupportsSavepoints => true;

    /// <inheritdoc />
    public bool SupportsStreaming => true;

    /// <inheritdoc />
    public bool SupportsBulkCopy => true;

    /// <inheritdoc />
    public bool SupportsKeysetPagination => true;

    /// <inheritdoc />
    public bool SupportsJsonQuery => true;

    /// <inheritdoc />
    public bool SupportsRowLevelSecurity => true;

    /// <inheritdoc />
    public bool SupportsUpsert => true;

    /// <inheritdoc />
    public bool SupportsIdentityRetrieval => true;

    /// <summary>
    /// Online index rebuilds exist, but most column and constraint changes
    /// still take a schema-modification lock. Declared false: the
    /// expand–migrate–contract discipline (ADR-021) is required either way,
    /// and an over-claim here would let a migration take an outage.
    /// </summary>
    public bool SupportsZeroDowntimeDdl => false;

    /// <inheritdoc />
    public int MaxParameterCount => 2100;

    /// <inheritdoc />
    public int MaxBatchSize => 1000;

    /// <inheritdoc />
    public int MaxIdentifierLength => 128;
}
