using System;
using System.Collections.Generic;

namespace Edpf.Abstractions.Data;

/// <summary>
/// The per-engine SQL surface (Phase 06 §④). Everything that differs between
/// relational engines and cannot be hidden behind a common abstraction lives
/// here, so the rest of the framework is written once.
/// </summary>
/// <remarks>
/// Every method that emits SQL takes structural elements only — identifiers
/// and parameter names — never caller-supplied values. Values always travel
/// as parameters (ADR-018). A dialect that concatenated a value would defeat
/// the framework's central injection defence, so the contract offers no
/// method that could.
/// </remarks>
public interface ISqlDialect
{
    /// <summary>Provider name this dialect belongs to, e.g. <c>SqlServer</c>.</summary>
    string ProviderName { get; }

    /// <summary>The parameter prefix — <c>@</c> on SQL Server, <c>$</c> or <c>:</c> elsewhere.</summary>
    string ParameterPrefix { get; }

    /// <summary>
    /// Quotes an identifier for this engine, rejecting anything that is not a
    /// legal identifier rather than escaping it.
    /// </summary>
    /// <param name="identifier">A table, column or schema name resolved from metadata.</param>
    /// <returns>The quoted identifier.</returns>
    /// <exception cref="ArgumentException">
    /// The identifier is empty, over-long, or contains characters no legal
    /// identifier may contain. Rejecting beats escaping: an identifier that
    /// needs escaping came from somewhere it should not have.
    /// </exception>
    string QuoteIdentifier(string identifier);

    /// <summary>Formats a parameter reference for use in a statement.</summary>
    /// <param name="parameterName">The bare parameter name.</param>
    string Parameter(string parameterName);

    /// <summary>
    /// Renders offset pagination for this engine — <c>OFFSET/FETCH</c>,
    /// <c>LIMIT/OFFSET</c> or a <c>ROWNUM</c> wrapper.
    /// </summary>
    /// <param name="skipParameter">Parameter name holding the row offset.</param>
    /// <param name="takeParameter">Parameter name holding the page size.</param>
    /// <returns>The clause to append to an ordered statement.</returns>
    string PaginationClause(string skipParameter, string takeParameter);

    /// <summary>
    /// Renders keyset pagination — the only form that stays correct past a few
    /// hundred thousand rows.
    /// </summary>
    /// <param name="orderedColumns">Ordering columns, in order, each with its direction.</param>
    /// <param name="cursorParameters">Parameter names holding the cursor values, positionally matched.</param>
    /// <returns>A predicate selecting rows strictly after the cursor.</returns>
    string KeysetPredicate(
        IReadOnlyList<SortColumn> orderedColumns,
        IReadOnlyList<string> cursorParameters);

    /// <summary>Statement fragment retrieving the identity generated by the preceding insert.</summary>
    string IdentityRetrievalClause();

    /// <summary>Current UTC timestamp expression for this engine.</summary>
    string UtcNowExpression();

    /// <summary>Concatenates expressions using this engine's operator or function.</summary>
    /// <param name="expressions">Already-safe SQL expressions (identifiers or parameters).</param>
    string Concat(IReadOnlyList<string> expressions);

    /// <summary>Renders a boolean literal the way this engine expresses it.</summary>
    /// <param name="value">The boolean value.</param>
    string BooleanLiteral(bool value);

    /// <summary>Renders a JSON path extraction over a column.</summary>
    /// <param name="columnExpression">The quoted column.</param>
    /// <param name="jsonPathParameter">Parameter holding the path — never inlined.</param>
    string JsonValue(string columnExpression, string jsonPathParameter);
}

/// <summary>One column of an ORDER BY, with its direction.</summary>
public readonly struct SortColumn : IEquatable<SortColumn>
{
    /// <summary>
    /// Initializes a sort column.
    /// </summary>
    /// <param name="columnName">The column name, resolved from entity metadata — never caller text.</param>
    /// <param name="descending">True to sort descending.</param>
    /// <exception cref="ArgumentException"><paramref name="columnName"/> is null or blank.</exception>
    public SortColumn(string columnName, bool descending = false)
    {
        if (string.IsNullOrWhiteSpace(columnName))
        {
            throw new ArgumentException("Column name must not be blank.", nameof(columnName));
        }

        ColumnName = columnName;
        Descending = descending;
    }

    /// <summary>The column name.</summary>
    public string ColumnName { get; }

    /// <summary>True when the sort is descending.</summary>
    public bool Descending { get; }

    /// <inheritdoc />
    public bool Equals(SortColumn other)
        => string.Equals(ColumnName, other.ColumnName, StringComparison.Ordinal)
        && Descending == other.Descending;

    /// <inheritdoc />
    public override bool Equals(object? obj) => obj is SortColumn other && Equals(other);

    /// <inheritdoc />
    public override int GetHashCode()
    {
        unchecked
        {
            return (StringComparer.Ordinal.GetHashCode(ColumnName) * 397) ^ Descending.GetHashCode();
        }
    }

    /// <summary>Value equality.</summary>
    public static bool operator ==(SortColumn left, SortColumn right) => left.Equals(right);

    /// <summary>Value inequality.</summary>
    public static bool operator !=(SortColumn left, SortColumn right) => !left.Equals(right);

    /// <summary>Formats as <c>Column ASC|DESC</c>.</summary>
    public override string ToString() => ColumnName + (Descending ? " DESC" : " ASC");
}
